using Sts2CharForge.Core.Effects;
using Sts2CharForge.Core.Profile;

namespace Sts2CharForge.Core.Generation;

/// <summary>生成「把自定义角色塞进本体先古之民对话表」的补丁。</summary>
public static partial class AncientPatchGen
{
    /// <summary>这位先古之民有没有配置对话（配置了才需要注入）。</summary>
    public static bool HasDialogues(CharacterProfile p) =>
        p.Ancients.Any(a => !string.IsNullOrWhiteSpace(a.AncientId)
                            && EffectCatalog.FindAncient(a.AncientId) is not null
                            && a.Dialogues.Any(d => d.Lines.Any(l => !string.IsNullOrWhiteSpace(l.Text))));

    /// <summary>
    /// 生成 <c>cs/AncientDialoguePatch.cs</c>。
    ///
    /// 原理（照本体 AncientDialogueSet / AncientEventModel 的写法）：
    ///   本体的对话表 <c>AncientEventModel.DialogueSet.CharacterDialogues</c> 是按「角色 ID」查的字典
    ///   （IRONCLAD / SILENT / …）；自定义角色不在里面，所以本体只会去找 JSON 里「任意角色（ANY）」那组，
    ///   而建筑师连 ANY 都没有 → 自定义角色和先古之民/建筑师**一句话都说不上**。
    ///   这里在 DialogueSet 取完之后（Postfix）把我们的角色加进那个字典，并沿着本体自己的
    ///   <c>AncientDialogue.PopulateLines(先古之民, 角色, 第几段)</c> 去读我们写的本地化键。
    /// </summary>
    public static string Source(CharacterProfile p)
    {
        var n = Naming.From(p);

        // 每个先古之民：一段一段的 (第几次到访, 是否可重复, 句数)
        var rows = new List<string>();
        foreach (var talk in p.Ancients)
        {
            if (string.IsNullOrWhiteSpace(talk.AncientId)) continue;
            if (EffectCatalog.FindAncient(talk.AncientId) is null) continue;

            var dialogues = new List<string>();
            foreach (var d in talk.Dialogues)
            {
                int lines = d.Lines.Count(l => !string.IsNullOrWhiteSpace(l.Text));
                if (lines == 0) continue;
                dialogues.Add($"({d.NativeVisitIndex}, {(d.Repeating ? "true" : "false")}, {lines})");
            }
            if (dialogues.Count == 0) continue;
            rows.Add($"            [{Lit.Str(talk.AncientId)}] = new (int VisitIndex, bool Repeating, int Lines)[] {{ {string.Join(", ", dialogues)} }},");
        }

        return $$"""
// <auto-generated> 先古之民对话：把自定义角色塞进本体的对话表 </auto-generated>
namespace {{n.Namespace}};

/// <summary>
/// 让自定义角色能和先古之民（含建筑师）说话。
///
/// 本体的对话表 AncientEventModel.DialogueSet.CharacterDialogues 是按「角色 ID」查的字典
/// （IRONCLAD / SILENT / …），自定义角色不在里面；本体的兜底是 JSON 里「任意角色（ANY）」那组，
/// 而建筑师连 ANY 都没有 —— 所以不打这个补丁的话，自定义角色跟谁都说不上话。
///
/// 这里在 DialogueSet 取完之后把我们自己加进那个字典，并用本体自己的
/// AncientDialogue.PopulateLines() 去读我们写的键：
///   {{n.CharEntry}}.talk 用的是 "&lt;先古之民&gt;.talk.{{n.CharEntry}}.<第几段>-<第几句>[r].ancient|char"。
/// 对话句数由我们说了算（本体给「任意角色」那组每段只有 1 句，这里不受限制）。
/// </summary>
[HarmonyLib.HarmonyPatch(typeof(MegaCrit.Sts2.Core.Models.AncientEventModel), nameof(MegaCrit.Sts2.Core.Models.AncientEventModel.DialogueSet), HarmonyLib.MethodType.Getter)]
public static class AncientDialoguePatch
{
    /// <summary>我们和每位先古之民说的话：第几次到访 / 是否可重复 / 这段几句。</summary>
    private static readonly Dictionary<string, (int VisitIndex, bool Repeating, int Lines)[]> OurDialogues = new()
    {
{{string.Join("\n", rows)}}
    };

    [HarmonyLib.HarmonyPostfix]
    private static void AfterGetDialogueSet(MegaCrit.Sts2.Core.Models.AncientEventModel __instance, MegaCrit.Sts2.Core.Entities.Ancients.AncientDialogueSet __result)
    {
        try
        {
            if (__result is null) return;
            string ancient = __instance.Id.Entry;      // 例：THE_ARCHITECT / DARV
            if (!OurDialogues.TryGetValue(ancient, out var mine)) return;
            // 已经注入过就别重复（同一个先古之民在一次游戏里只会构建一次对话表）
            if (__result.CharacterDialogues.ContainsKey("{{n.CharEntry}}")) return;

            // 借一份本体对话的「音效」：让我们的台词也有声音（引用本体自己的音频路径，不复制素材）
            var sfxSource = __result.CharacterDialogues.Values.FirstOrDefault(v => v.Count > 0)?.FirstOrDefault();

            var list = new List<MegaCrit.Sts2.Core.Entities.Ancients.AncientDialogue>();
            for (int i = 0; i < mine.Length; i++)
            {
                var (visitIndex, repeating, lines) = mine[i];
                string[] sfx = new string[lines];
                for (int k = 0; k < lines; k++)
                {
                    if (sfxSource is not null && k < sfxSource.Lines.Count)
                        sfx[k] = sfxSource.Lines[k].GetSfxOrFallbackPath();
                    else
                        sfx[k] = MegaCrit.Sts2.Core.Entities.Ancients.AncientDialogueLine.sfxFallbackPath;
                }

                var dlg = new MegaCrit.Sts2.Core.Entities.Ancients.AncientDialogue(sfx)
                {
                    VisitIndex = visitIndex >= 0 ? visitIndex : null,
                    IsRepeating = repeating,
                };
                dlg.PopulateLines(ancient, "{{n.CharEntry}}", i);

                // 非最后一句要给「下一句」按钮文字（本体 PopulateLocKeys 只处理它自己那些对话，注入的得自己补）
                for (int k = 0; k < dlg.Lines.Count - 1; k++)
                {
                    var line = dlg.Lines[k];
                    if (line.LineText is null) continue;
                    string key = line.LineText.LocEntryKey;
                    int dot = key.LastIndexOf('.');
                    if (dot > 0)
                        line.NextButtonText = new MegaCrit.Sts2.Core.Localization.LocString("ancients", key.Substring(0, dot) + ".next");
                }
                list.Add(dlg);
            }

            __result.CharacterDialogues["{{n.CharEntry}}"] = list;
            Log.Info("{{n.ModId}} - 已给先古之民 " + ancient + " 注入 " + list.Count + " 段自定义角色对话");
        }
        catch (Exception e)
        {
            // 注入失败不能影响游戏本身的对话：只记日志
            Log.Error("{{n.ModId}} - 先古之民对话注入失败（已忽略）：" + e.Message);
        }
    }
}

""";
    }

    // ==================== 先古之民的遗物选项替换 ====================

    /// <summary>有没有配「替换某位先古之民的某个遗物选项」。</summary>
    public static bool HasRelicReplacements(CharacterProfile p) =>
        p.Ancients.Any(a => !string.IsNullOrWhiteSpace(a.AncientId)
                            && EffectCatalog.FindAncient(a.AncientId) is not null
                            && a.RelicReplacements.Any(r => !string.IsNullOrWhiteSpace(r.RelicId)));

    /// <summary>
    /// 遗物「类名 ↔ 本体本地化表键」的归一化比较：SNECKO_EYE == SneckoEye、BLACK_STAR == BlackStar。
    /// 界面/存档里配的是**类名**，而运行时 <c>RelicModel.Id.Entry</c> 是**本地化表键**（大写下划线），
    /// 直接比字符串永远匹配不上（踩过：表现成「替换无效」）。生成出来的补丁里也有一份同样的实现。
    /// </summary>
    public static bool SameRelic(string? a, string? b)
    {
        if (string.IsNullOrWhiteSpace(a) || string.IsNullOrWhiteSpace(b)) return false;
        return string.Equals(NormalizeRelicKey(a), NormalizeRelicKey(b), StringComparison.OrdinalIgnoreCase);
    }

    private static string NormalizeRelicKey(string s) =>
        s.Replace("_", "").Replace("-", "").Replace(" ", "").Trim();

    /// <summary>生成 <c>cs/AncientRelicReplace.cs</c>：给配了替换的每位先古之民补一个
    /// <c>GenerateInitialOptions</c> 的 Postfix —— 把他原本会给的某个遗物换成你要的遗物。
    ///
    /// 为什么这么打（都对着本体源码确认过）：
    ///   · 本体每位先古之民的候选遗物表是各自类里的私有字段（Darv 的 _validRelicSets 等），外部改不了；
    ///     但选项最终由 protected 的 <c>GenerateInitialOptions()</c> 产出（筛选 → 洗牌 → 取 2~3 个，
    ///     有时第 3 个是「尘封古书」），在它跑完之后改结果最稳：选项数还是 3、其它逻辑一概不动。
    ///   · 造选项用**本体自己的** protected 方法 <c>RelicOption(RelicModel, pageName, customDonePage)</c>（反射调用），
    ///     所以「选中 → 获得遗物 → 结束事件」的行为和本体完全一致，不用我们重写。
    ///   · 按「原本的遗物」定位：这次选项里有它就换掉它；没抽到（他每次随机取 3 个）就顶掉最后一个，
    ///     保证你配的遗物一定会出现在选项里。
    /// </summary>
    public static string RelicReplacementSource(CharacterProfile p)
    {
        var n = Naming.From(p);
        var patches = new List<string>();

        foreach (var talk in p.Ancients)
        {
            if (string.IsNullOrWhiteSpace(talk.AncientId)) continue;
            var ancient = EffectCatalog.FindAncient(talk.AncientId);
            if (ancient is null) continue;

            string cls = string.IsNullOrWhiteSpace(ancient.EventClassName)
                ? AncientClassName(talk.AncientId)
                : ancient.EventClassName;
            if (cls.Length == 0) continue;

            var calls = new List<string>();
            var usedFrom = new HashSet<string>(StringComparer.Ordinal);
            foreach (var r in talk.RelicReplacements)
            {
                if (string.IsNullOrWhiteSpace(r.RelicId) && string.IsNullOrWhiteSpace(r.FromRelicId) && r.Slot <= 0) continue;
                string from = r.FromRelicId ?? "";
                if (from.Length > 0 && !usedFrom.Add(from))
                {
                    calls.Add($"                // 「{from}」配了不止一次，这里只留第一条");
                    continue;
                }
                string note = string.IsNullOrWhiteSpace(from)
                    ? (r.Slot >= 1 ? $"第 {Math.Clamp(r.Slot, 1, 3)} 个位置（旧配置按位置换）" : "（没配要替换哪个 → 这条不会生效）")
                    : AncientCatalog.VanillaRelicName(from) ?? from;
                calls.Add($"                ForgeAncientRelicReplace.Replace<{r.RelicId}>(options, __instance, {Lit.Str(from)}, {Math.Max(0, r.Slot)});   // 「{note}」：这次选项里有它才换，没抽到就不动");
            }
            if (calls.Count == 0) continue;

            patches.Add($$"""
    /// <summary>{{ancient.Epithet}}（{{talk.AncientId}}）：把他原本会给的某个遗物换成你配的遗物。</summary>
    [HarmonyLib.HarmonyPatch(typeof(MegaCrit.Sts2.Core.Models.Events.{{cls}}), "GenerateInitialOptions")]
    public static class Forge{{cls}}RelicReplacePatch
    {
        [HarmonyLib.HarmonyPostfix]
        private static void AfterGenerateInitialOptions(MegaCrit.Sts2.Core.Models.Events.{{cls}} __instance,
            ref IReadOnlyList<MegaCrit.Sts2.Core.Events.EventOption> __result)
        {
            try
            {
                if (__result is null || __result.Count == 0) return;
                var options = __result.ToList();
{{string.Join("\n", calls)}}
                __result = options;
            }
            catch (Exception e)
            {
                // 改选项失败绝不能把事件搞崩：原样返回本体的结果
                Log.Error("{{n.ModId}} - 先古之民 {{talk.AncientId}} 的遗物选项替换失败（已忽略）：" + e.Message);
            }
        }
    }
""");
        }

        if (patches.Count == 0) return "";

        return $$"""
// <auto-generated> 先古之民的遗物选项替换 </auto-generated>
namespace {{n.Namespace}};

/// <summary>
/// 把某位先古之民固定给的一个遗物选项换成你要的遗物。
/// 本体每位先古之民固定给 3 个遗物选项（从他自己的候选表里随机抽，有时多带一本「尘封古书」）；
/// 我们不动他的候选表，只在他生成完选项之后把指定位置的那个换掉 —— 选项数还是 3 个。
/// 造选项用本体自己的 RelicOption(...)（反射），所以行为（选中→获得遗物→事件结束）和本体一致。
/// </summary>
internal static class ForgeAncientRelicReplace
{
    private static System.Reflection.MethodInfo? _relicOption;

    /// <summary>用本体自己的 RelicOption(RelicModel, string, string) 造一个遗物选项。</summary>
    internal static MegaCrit.Sts2.Core.Events.EventOption MakeOption(
        MegaCrit.Sts2.Core.Models.AncientEventModel ancient, MegaCrit.Sts2.Core.Models.RelicModel relic)
    {
        _relicOption ??= HarmonyLib.AccessTools.Method(typeof(MegaCrit.Sts2.Core.Models.AncientEventModel), "RelicOption",
            [typeof(MegaCrit.Sts2.Core.Models.RelicModel), typeof(string), typeof(string)]);
        if (_relicOption is null) throw new InvalidOperationException("找不到本体的 RelicOption 方法");
        return (MegaCrit.Sts2.Core.Events.EventOption)_relicOption.Invoke(ancient, [relic, "INITIAL", null])!;
    }

    /// <summary>把某个「原本的遗物」选项换成这个遗物。
    /// 这次选项里有它 → 换掉它；本来就有你要的遗物 → 不动；
    /// **这次没抽到它 → 什么都不做**（不顶掉别的选项，见下）。
    /// 旧配置只有「第 N 个位置」的话，按位置换（<paramref name="slot"/>，1 起）。</summary>
    /// <param name="fromRelicId">要替换掉的原本的遗物（界面上配的是**类名**，比如 SneckoEye）。
    /// 留空 = 没配（这时如果 slot 也没配，本次跳过）。</param>
    /// <param name="slot">旧版字段：按第几个选项替换（1 起，0 = 没配）。</param>
    internal static void Replace<T>(List<MegaCrit.Sts2.Core.Events.EventOption> options,
        MegaCrit.Sts2.Core.Models.AncientEventModel ancient, string fromRelicId, int slot = 0) where T : MegaCrit.Sts2.Core.Models.RelicModel
    {
        if (options.Count == 0) return;
        var relic = ModelDb.Relic<T>().ToMutable();
        string before = string.Join(" / ", options.Select(o => o.Relic is null ? "(非遗物选项)" : o.Relic.Id.Entry));
        if (options.Any(o => o.Relic is not null && o.Relic.Id == relic.Id))
        {
            Log.Info("{{n.ModId}} - " + ancient.Id.Entry + " 的遗物选项里本来就有 " + relic.Id.Entry + "，跳过替换（这次选项：" + before + "）");
            return;
        }

        // 找「原本的遗物」那一条。
        // 注意：本体遗物的 Id.Entry 是「SNECKO_EYE」这种大写下划线（本体本地化表的键），
        // 而界面上配的是类名「SneckoEye」—— 直接字符串比会永远匹配不上（踩过：表现成「替换无效」）。
        // 所以两边都归一化（去掉下划线 / 连字符 / 空格，忽略大小写）再比，类名也对一遍更稳。
        int index = -1;
        if (!string.IsNullOrEmpty(fromRelicId))
        {
            for (int i = 0; i < options.Count; i++)
            {
                var r = options[i].Relic;
                if (r is null) continue;
                if (SameRelic(r.Id.Entry, fromRelicId) || SameRelic(r.GetType().Name, fromRelicId))
                {
                    index = i;
                    break;
                }
            }
        }

        // 旧配置（只配了「第 N 个位置」）：按位置换 —— 这是老版本的行为，保持兼容
        if (index < 0 && slot >= 1)
        {
            index = Math.Clamp(slot, 1, options.Count) - 1;
            Log.Info("{{n.ModId}} - " + ancient.Id.Entry + " 的遗物选项：" + before + "  →  按旧配置的第 " + (index + 1) + " 个位置替换"
                + "（换成 " + relic.Id.Entry + "）");
            options[index] = MakeOption(ancient, relic);
            return;
        }

        // 这次没抽到「原本的遗物」→ **什么都不做**。
        // 以前这里会顶掉最后一个选项来「保证你要的遗物一定出现」，但那会顺手换掉一个
        // 本来该出现的选项（用户报过：明明没抽到那个遗物，却把别的选项挤掉了），
        // 所以现在改成这次不替换 —— 只在他真的给出那个遗物时才换。
        if (index < 0)
        {
            Log.Info("{{n.ModId}} - " + ancient.Id.Entry + " 的遗物选项：" + before
                + "（这次没有 " + (fromRelicId.Length > 0 ? fromRelicId : "(没配原本的遗物)") + "，本次不替换）");
            return;
        }

        string why = "顶掉了原本的 " + options[index].Relic!.Id.Entry;
        options[index] = MakeOption(ancient, relic);
        string after = string.Join(" / ", options.Select(o => o.Relic is null ? "(非遗物选项)" : o.Relic.Id.Entry));
        Log.Info("{{n.ModId}} - " + ancient.Id.Entry + " 的遗物选项：" + before + "  →  " + after
            + "（" + why + "，换成 " + relic.Id.Entry + "）");
    }

    /// <summary>遗物类名 / 本地化表键的归一化比较（SNECKO_EYE == SneckoEye）。</summary>
    public static bool SameRelic(string? a, string? b)
    {
        if (string.IsNullOrEmpty(a) || string.IsNullOrEmpty(b)) return false;
        return string.Equals(Norm(a), Norm(b), StringComparison.OrdinalIgnoreCase);

        static string Norm(string s) => s.Replace("_", "").Replace("-", "").Replace(" ", "");
    }
}

{{string.Join("\n", patches)}}
""";
    }

    /// <summary>本体事件类名：先古之民 Id（DARV）→ 类名（Darv）。目录里扫不到时用它兜底。</summary>
    private static string AncientClassName(string ancientId)
    {
        string id = (ancientId ?? "").Trim();
        if (id.Length == 0) return "";
        var parts = id.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var sb = new System.Text.StringBuilder();
        foreach (string part in parts)
            sb.Append(char.ToUpperInvariant(part[0])).Append(part.Substring(1).ToLowerInvariant());
        return sb.ToString();
    }
}