using Sts2CharForge.Core.Effects;
using Sts2CharForge.Core.Profile;

namespace Sts2CharForge.Core.Generation;

/// <summary>
/// 「自定义状态（能力）」的生成：把配置里的每个状态变成一个 PowerModel 子类。
///
/// 每个状态 = 一个 <c>cs/Powers/&lt;类名&gt;.cs</c>，里面按「触发时机」重写本体的钩子
/// （钩子都在 AbstractModel 上、由 Hook.cs 派发，PowerModel.ShouldReceiveCombatHooks 为 true）。
/// 名字/描述写进 localization/zhs/powers.json；图标和层数数字颜色由状态外观补丁接管
/// （PowerModel.Icon 不是 virtual，没法在子类里重写，只能补丁）。
/// </summary>
public static class CustomPowerGen
{
    public static bool IsActive(CustomPowerSpec p) => p.Enabled && !string.IsNullOrWhiteSpace(p.Name);

    public static List<CustomPowerSpec> Active(CharacterProfile profile) =>
        profile.CustomPowers.Where(IsActive).ToList();

    public static bool HasAny(CharacterProfile p) => Active(p).Count > 0;

    /// <summary>类名（配置空着就用 角色类名 + Power + 序号）。</summary>
    public static string ClassNameOf(CharacterProfile p, CustomPowerSpec power, int index)
    {
        string cls = (power.ClassName ?? "").Trim();
        if (cls.Length > 0 && Naming.IsValidIdentifier(cls)) return cls;
        return Naming.From(p).CharClass + "Power" + (index + 1);
    }

    /// <summary>本体 Id.Entry（本地化键前缀）：类名按驼峰拆开大写，和本体一致。</summary>
    public static string EntryOf(CharacterProfile p, CustomPowerSpec power, int index) =>
        EffectCatalog.SlugFor(ClassNameOf(p, power, index));

    /// <summary>图标在工程里的相对路径。</summary>
    public static string IconRelPath(CharacterProfile p, CustomPowerSpec power, int index) =>
        $"images/powers_override/{EntryOf(p, power, index).ToLowerInvariant()}_icon.png";

    /// <summary>图标 res:// 路径（没上传返回 null）。</summary>
    public static string? IconResPath(CharacterProfile p, CustomPowerSpec power, int index) =>
        string.IsNullOrWhiteSpace(power.Icon) ? null : "res://" + IconRelPath(p, power, index);

    /// <summary>描述（没填就按触发器自动生成一句）。</summary>
    public static string DescriptionOf(CustomPowerSpec power) =>
        string.IsNullOrWhiteSpace(power.Description) ? PowerTriggers.AutoDescription(power) : power.Description.Trim();

    /// <summary>生成一个自定义状态的 PowerModel 子类。</summary>
    public static string Source(CharacterProfile profile, CustomPowerSpec power, int index)
    {
        var n = Naming.From(profile);
        string cls = ClassNameOf(profile, power, index);
        bool debuff = power.Type == "Debuff";

        var w = new CodeWriter();
        w.Line($"// <auto-generated> 自定义状态「{power.Name}」（能力牌用） </auto-generated>");
        w.Line($"namespace {n.Namespace};");
        w.Line();
        w.Line($"/// <summary>{power.Name}：{DescriptionOf(power).Replace("\n", " ")}</summary>");
        w.Open($"public sealed class {cls} : PowerModel");
        w.Line($"public override PowerType Type => PowerType.{(debuff ? "Debuff" : "Buff")};");
        w.Line();
        w.Line($"public override PowerStackType StackType => PowerStackType.{(power.Single ? "Single" : "Counter")};");

        if (power.Triggers.Count == 0)
        {
            w.Line();
            w.Line("// 没配触发时机：这个状态只会挂着（加个触发时机才会真的做事）");
        }

        // 同一个触发时机只能生成一个方法（同名同参数方法写两个 C# 直接编译不过），
        // 所以按 Kind 分组：同一种时机配了好几条就依次执行；「回合结束」还要和衰减/移除合进同一个方法。
        var order = new List<string>();
        var map = new Dictionary<string, List<PowerTriggerSpec>>(StringComparer.Ordinal);
        foreach (var t in power.Triggers)
        {
            if (!map.TryGetValue(t.Kind, out var list)) { list = new List<PowerTriggerSpec>(); map[t.Kind] = list; order.Add(t.Kind); }
            list.Add(t);
        }

        foreach (string kind in order)
        {
            if (kind == "TurnEnd")
            {
                // 和衰减 / 移除合并成一个方法
                EmitTurnEndMethod(w, map[kind], power);
                continue;
            }
            EmitTriggerMethod(w, kind, map[kind]);
        }

        // 只配了衰减 / 移除、没有 TurnEnd 触发时机时，也要有那个方法
        if (!map.ContainsKey("TurnEnd") && (power.RemoveAtTurnEnd || power.DecayPerTurn > 0))
            EmitTurnEndMethod(w, new List<PowerTriggerSpec>(), power);

        w.Close();
        return w.ToString();
    }

    /// <summary>「玩家回合结束时」：TurnEnd 触发器的效果先跑，然后才是衰减 / 移除。</summary>
    private static void EmitTurnEndMethod(CodeWriter w, List<PowerTriggerSpec> items, CustomPowerSpec power)
    {
        w.Line();
        w.Line("// ===== 触发时机：玩家回合结束时（触发器效果跑完再做衰减 / 移除）=====");

        if (power.RemoveAtTurnEnd)
        {
            w.Open("public override async Task BeforeSideTurnEnd(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants)");
            w.Line("if (side != CombatSide.Player) return;");
            foreach (var t in items) EmitEffects(w, t);
            w.Line();
            w.Line("await PowerCmd.Remove(this);   // 临时状态：本回合结束就没了");
            w.Close();
            return;
        }

        w.Open("public override async Task BeforeSideTurnEnd(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants)");
        w.Line("if (side != CombatSide.Player) return;");
        foreach (var t in items) EmitEffects(w, t);

        if (power.DecayPerTurn > 0)
        {
            w.Line();
            w.Line($"// 每回合减 {power.DecayPerTurn} 层（减到 0 就移除）");
            w.Open($"if (base.Amount <= {power.DecayPerTurn})");
            w.Line("await PowerCmd.Remove(this);");
            w.Close();
            w.Line("else");
            w.Open("");
            w.Line($"SetAmount(base.Amount - {power.DecayPerTurn});");
            w.Close();
        }
        w.Close();
    }

    /// <summary>把一种触发时机（可能配了好几条）生成成一个钩子方法。</summary>
    private static void EmitTriggerMethod(CodeWriter w, string kind, List<PowerTriggerSpec> items)
    {
        string when = PowerTriggers.Find(kind)?.Display ?? kind;
        w.Line();
        w.Line($"// ===== 触发时机：{when} =====");

        switch (kind)
        {
            case "TurnStart":
                w.Open("public override async Task AfterPlayerTurnStart(PlayerChoiceContext choiceContext, Player player)");
                w.Line("if (player != base.Owner.Player) return;");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "CardPlayed":
                w.Open("public override async Task AfterCardPlayed(PlayerChoiceContext choiceContext, CardPlay cardPlay)");
                w.Line("if (cardPlay.Player != base.Owner.Player) return;");
                // 不挑牌型的先无条件跑；挑牌型的各自包一层 if
                foreach (var t in items.Where(x => x.CardFilter == "Any"))
                    EmitEffects(w, t, foeFrom: "cardPlay.Target");
                foreach (var t in items.Where(x => x.CardFilter != "Any"))
                {
                    w.Open($"if (cardPlay.Card.Type == CardType.{t.CardFilter})");
                    EmitEffects(w, t, foeFrom: "cardPlay.Target");
                    w.Close();
                }
                w.Close();
                break;

            case "CardExhausted":
                w.Open("public override async Task AfterCardExhausted(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal)");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "CardDrawn":
                w.Open("public override async Task AfterCardDrawn(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw)");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "CardDiscarded":
                w.Open("public override async Task AfterCardDiscarded(PlayerChoiceContext choiceContext, CardModel card)");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "DamageTaken":
                w.Open("public override async Task AfterDamageReceived(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource)");
                w.Line("if (target != base.Owner) return;");
                foreach (var t in items) EmitEffects(w, t, foeFrom: "dealer");
                w.Close();
                break;

            case "DamageDealt":
                w.Open("public override async Task AfterDamageGiven(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource)");
                w.Line("if (dealer != base.Owner) return;");
                foreach (var t in items) EmitEffects(w, t, foeFrom: "target");
                w.Close();
                break;

            case "BlockGained":
                w.Open("public override async Task AfterBlockGained(Creature creature, decimal amount, ValueProp props, CardModel? cardSource)");
                w.Line("if (creature != base.Owner) return;");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "EnemyDeath":
                w.Open("public override async Task AfterDeath(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength)");
                w.Line("if (!creature.IsEnemy) return;");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "CombatStart":
                w.Open("public override async Task BeforeCombatStart()");
                EmitChoiceContextBootstrap(w, "CombatStart", items);
                w.Line("await Task.CompletedTask;   // 钩子是 async 的，保持签名一致");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "EnergySpent":
                w.Open("public override async Task AfterEnergySpent(CardModel card, int amount)");
                EmitChoiceContextBootstrap(w, "EnergySpent", items);
                w.Line("await Task.CompletedTask;");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "StarsSpent":
                w.Open("public override async Task AfterStarsSpent(int amount, Player spender)");
                EmitChoiceContextBootstrap(w, "StarsSpent", items);
                w.Line("if (spender != base.Owner.Player) return;");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "CombatVictory":
                // 用 AfterCombatEnd 而不是 AfterCombatVictory：本体的「王国资产」（RoyaltiesPower）就是这么写的，
                // 而且卡牌奖励要挂在 room 的奖励集合上（AddExtraReward），这个钩子里正好有 CombatRoom。
                w.Open("public override async Task AfterCombatEnd(CombatRoom room)");
                EmitChoiceContextBootstrap(w, "CombatVictory", items, roomInScope: true);
                w.Line("// 战斗胜利后（打输了不走这里）：给卡牌奖励之类用这个");
                foreach (var tr in items) EmitEffects(w, tr, roomVar: "room");
                w.Close();
                break;

            case "EnemyTurnStart":
                w.Open("public override async Task AfterSideTurnStart(CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState)");
                EmitChoiceContextBootstrap(w, "EnemyTurnStart", items);
                w.Line("if (side != CombatSide.Enemy) return;   // 只认敌人那一侧");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "EnemyTurnEnd":
                w.Open("public override async Task BeforeSideTurnEnd(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants)");
                EmitChoiceContextBootstrap(w, "EnemyTurnEnd", items);
                w.Line("if (side != CombatSide.Enemy) return;   // 只认敌人那一侧");
                foreach (var t in items) EmitEffects(w, t);
                w.Close();
                break;

            case "EnemyDamaged":
                w.Open("public override async Task AfterDamageReceived(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource)");
                EmitChoiceContextBootstrap(w, "EnemyDamaged", items);
                w.Line("if (target == base.Owner || !target.IsAlive) return;   // 受伤的是敌人（自己不算）");
                foreach (var t in items) EmitEffects(w, t, foeFrom: "target");
                w.Close();
                break;

            case "EnemyDealtDamage":
                w.Open("public override async Task AfterDamageGiven(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource)");
                EmitChoiceContextBootstrap(w, "EnemyDealtDamage", items);
                w.Line("if (dealer is null || dealer == base.Owner) return;   // 打人的是敌人（自己不算）");
                foreach (var t in items) EmitEffects(w, t, foeFrom: "dealer");
                w.Close();
                break;

            case "EnemyBlockGained":
                w.Open("public override async Task AfterBlockGained(Creature creature, decimal amount, ValueProp props, CardModel? cardSource)");
                EmitChoiceContextBootstrap(w, "EnemyBlockGained", items);
                w.Line("if (creature == base.Owner) return;   // 拿格挡的是敌人（自己不算）");
                foreach (var t in items) EmitEffects(w, t, foeFrom: "creature");
                w.Close();
                break;

            case "PowerChanged":
                w.Open("public override async Task AfterPowerAmountChanged(PlayerChoiceContext choiceContext, PowerModel power, decimal amount, Creature? applier, CardModel? cardSource)");
                // 每条触发时机各自判断「盯谁 + 盯哪个状态」：不能写成函数开头的统一 return ——
                // 那样两种对象（自己 / 任意敌人）会互相把对方挡掉（实测生成出来敌人那条永远不跑）。
                foreach (var t in items)
                {
                    bool enemy = t.PowerTarget == "AnyEnemy";
                    string ownerGuard = enemy
                        ? "power.Owner is not null && power.Owner != base.Owner && power.Owner.IsAlive"
                          + " && base.Owner.CombatState is not null && base.Owner.CombatState.HittableEnemies.Contains(power.Owner)"
                        : "power != this && power.Owner == base.Owner";
                    string? want = string.IsNullOrWhiteSpace(t.PowerId) ? null : t.PowerId.Trim();
                    string guard = want is null ? ownerGuard : $"({ownerGuard}) && (power is {want})";
                    string what = want is null ? "任意状态" : EffectCatalog.PowerName(want, want);
                    w.Line($"// 盯：{PowerTriggers.WatchTargetZh(t.PowerTarget)}的{what}");
                    w.Open($"if ({guard})");
                    EmitEffects(w, t);
                    w.Close();
                }
                w.Close();
                break;

            default:
                w.Line("// （未知的触发时机，已跳过）");
                break;
        }
    }
    private static void EmitEffects(CodeWriter w, PowerTriggerSpec t, string? foeFrom = null, string? roomVar = null)
    {
        if (t.Effects.Count == 0)
        {
            w.Line("// （这个触发时机下还没加效果）");
            return;
        }
        w.Line();
        // 概率生效：这一个触发时机里所有勾了概率的效果共用一次掷骰
        var powerChanceSlices = CSharpCodeGen.ChanceSlices(t.Effects);
        if (powerChanceSlices.Count > 0) w.Line(CSharpCodeGen.ChanceRollLine("base.Owner.Player"));
        foreach (var e in t.Effects)
        {
            // 每条效果自己的条件：不满足时只跳过这一条
            string? cond = CSharpCodeGen.EffectConditionGuard(e, CSharpCodeGen.CondCtx.Power, chanceSlices: powerChanceSlices);
            if (cond is not null)
            {
                w.Line($"// 条件（只对「{EffectCatalog.FindKind(e.Kind).Display}」这条效果）：{CSharpCodeGen.ConditionText(e.Condition)}（不满足时这条效果不生效）");
                w.Open(cond);
            }
            EmitEffect(w, e, foeFrom, roomVar);
            if (cond is not null) w.Close();
        }
    }

    /// <summary>
    /// 这个触发时机的钩子有没有 choiceContext 参数？
    /// 本体有些钩子不带它：AfterSideTurnStart(side, participants, combatState)、
    /// AfterBlockGained(creature, amount, props, cardSource)、BeforeCombatStart()、
    /// AfterEnergySpent(int, Player)、AfterStarsSpent(int, Player)。
    /// </summary>
    internal static bool TriggerHasChoiceContext(string? kind) =>
        kind is not ("EnemyTurnStart" or "EnemyBlockGained" or "EnergySpent" or "StarsSpent" or "CombatStart" or "CombatVictory");

    /// <summary>
    /// 这个钩子没有 choiceContext 时，自己造一个再往下跑。
    /// 本体给模型派发钩子时就是这么造的（Hook.cs：new HookPlayerChoiceContext(model, netId, combatState, GameActionType.Combat)），
    /// 所以「敌人回合开始时造成伤害 / 上状态」这类效果也能正常用（不造的话会 CS0103）。
    /// roomInScope = 钩子里有 CombatRoom 的那几条：那种地方卡牌奖励走 room.AddExtraReward，不需要 choiceContext。
    /// </summary>
    private static void EmitChoiceContextBootstrap(CodeWriter w, string kind, IEnumerable<PowerTriggerSpec> items, bool roomInScope = false)
    {
        if (TriggerHasChoiceContext(kind)) return;
        if (!items.Any(t => t.Effects.Any(x => NeedsChoiceContext(x.Kind) && !(roomInScope && x.Kind == "CardReward")))) return;
        w.Line("// 这个钩子本体没给 choiceContext：按本体的做法自己造一个（不然造成伤害 / 施加状态 / 抽牌用不了）");
        w.Line("ulong __netId = MegaCrit.Sts2.Core.Context.LocalContext.NetId ?? 0UL;");
        w.Line("var choiceContext = new MegaCrit.Sts2.Core.GameActions.Multiplayer.HookPlayerChoiceContext(this, __netId, base.CombatState, MegaCrit.Sts2.Core.Entities.Multiplayer.GameActionType.Combat);");
    }

    /// <summary>这些效果必须要有 choiceContext 才能生成（校验器也用它）。</summary>
    internal static bool NeedsChoiceContext(string? kind) =>
        kind is "Damage" or "Draw" or "ApplyPower" or "TempPower" or "ExtraTurn" or "CardReward";

    /// <summary>
    /// 「随机挑一个敌人」那一行。
    ///
    /// 坑（用户实测编译失败）：状态钩子里 <c>base.Owner</c> 是 **Creature**，直接写
    /// <c>base.Owner.RunState</c> 报 CS1061（Creature 没有 RunState，整次构建失败）。
    /// 本体状态是这么写的（CacophonyPower / CountdownPower / HauntPower）：
    /// <c>base.Owner.Player.RunState.Rng.CombatTargets.NextItem(base.CombatState.HittableEnemies)</c>。
    /// 再兜一层 <c>base.CombatState?.RunState</c>：状态万一被挂在敌人身上时 Player 是 null（两边都取不到就返回 null，
    /// 后面那行 <c>if (other is null) break;</c> 会安全跳过，不会崩）。
    /// </summary>
    private const string RandomTargetLine =
        "Creature? other = (base.Owner.Player?.RunState ?? base.CombatState?.RunState)?.Rng.CombatTargets.NextItem(base.Owner.CombatState.HittableEnemies);";

    /// <summary>一条效果在状态钩子里的写法（上下文：choiceContext + base.Owner 是 Creature）。
    /// roomVar 非空 = 钩子里有 CombatRoom（战斗胜利后），卡牌奖励走本体的战斗奖励。</summary>
    private static void EmitEffect(CodeWriter w, EffectSpec e, string? foeFrom, string? roomVar = null)
    {
        string amt = e.AmountIsStack ? "base.Amount" : Lit.Dec(e.Amount);
        // 「直接把缓慢设成 N%」：本体的做法就是只施加 1 层（层数对「缓慢」没有作用），
        // 而且 amount == 0 时 PowerCmd.Apply 直接 return（状态根本挂不上）
        if (CSharpCodeGen.IsSlowPercentEffect(e)) amt = "1m";
        // 生效次数：勾了「= 本状态的层数」就按层数循环，否则用填的数字（层数本身不会让效果多跑，这点用户问过）
        int times = Math.Max(1, Math.Min(20, e.Times));
        bool loop = e.TimesIsStack || times > 1;
        // 每条效果外面永远包一层作用域：里面会声明 other / pick 这类临时变量，
        // 同一个触发时机里两条效果都声明同名变量时 C# 会 CS0136/CS0128 编译不过
        w.Open("");
        if (loop) w.Open($"for (int __rep = 0; __rep < {(e.TimesIsStack ? "(int)base.Amount" : times.ToString())}; __rep++)");

        switch (e.Kind)
        {
            case "Block":
                w.Line($"await CreatureCmd.GainBlock(base.Owner, {amt}, ValueProp.Unpowered, null);");
                break;

            case "Damage":
                EmitDamage(w, e, amt, foeFrom);
                break;

            case "Draw":
                w.Line($"await CardPileCmd.Draw(choiceContext, {amt}, base.Owner.Player);");
                break;

            case "Energy":
                w.Line($"await PlayerCmd.GainEnergy({amt}, base.Owner.Player);");
                break;

            case "Heal":
                w.Line($"await CreatureCmd.Heal(base.Owner, {amt});");
                break;

            case "HpLoss":
                w.Line($"await CreatureCmd.Damage(choiceContext, base.Owner, {amt}, ValueProp.Unblockable | ValueProp.Unpowered, base.Owner);");
                break;

            case "MaxHp":
                w.Open("if (base.Amount >= 0)");
                w.Line($"await CreatureCmd.GainMaxHp(base.Owner, {amt});");
                w.Close();
                w.Line("else");
                w.Open("");
                w.Line($"await CreatureCmd.LoseMaxHp(choiceContext, base.Owner, -({amt}), isFromCard: false);");
                w.Close();
                break;

            case "Gold":
                w.Line($"await PlayerCmd.GainGold({amt}, base.Owner.Player);");
                break;

            case "ExtraResource":
                w.Line($"await PlayerCmd.GainStars({amt}, base.Owner.Player);");
                break;

            case "ExtraTurn":
                w.Line($"await PowerCmd.Apply<{Naming.AmbientExtraTurnPowerClass}>(choiceContext, base.Owner, 1m, base.Owner, null);");
                break;

            case "GenerateCard":
                {
                    string card = string.IsNullOrWhiteSpace(e.SpawnCardId) ? "Shiv" : e.SpawnCardId!.Trim();
                    string count = e.AmountIsStack ? "(int)base.Amount" : Math.Max(1, (int)e.Amount).ToString();
                    w.Line($"await CardPileCmd.AddToCombatAndPreview<{card}>(base.Owner, PileType.{e.SpawnTo}, {count}, base.Owner.Player);");
                    break;
                }

            // 毒性爆发：状态里也能用（都是本体 API）。注意这里的 base.Owner 是 Creature（不是 Player），
            // 所以敌人列表 / 施加者都用它自己的形式（见 CSharpCodeGen.EmitOutbreak 的参数说明）。
            case "Outbreak":
                CSharpCodeGen.EmitOutbreak(w, e, amt,
                    enemies: "base.Owner.CombatState.HittableEnemies",
                    applier: "base.Owner", cardSource: "null");
                break;

            // 全局（牌组）类效果：状态里也能用（直接改玩家的牌组，不受战斗牌堆限制）
            case "AddCardGlobal":
            case "TransformCardGlobal":
            case "RemoveCardGlobal":
            case "UpgradeCardGlobal":
                CSharpCodeGen.EmitGlobalCardEffectPublic(w, e, "base.Owner.Player", e.AmountIsStack);
                break;

            case "CardReward":
                CSharpCodeGen.EmitCardRewardPublic(w, e, "base.Owner.Player", e.AmountIsStack, roomVar);
                break;

            case "ApplyPower":
                switch (e.TargetSide)
                {
                    case "Self":
                        w.Line($"await PowerCmd.Apply<{e.PowerId}>(choiceContext, base.Owner, {amt}, base.Owner, null);");
                        CSharpCodeGen.EmitSlowPercentFix(w, e, "base.Owner");
                        break;
                    case "AllEnemies":
                        w.Open("foreach (Creature other in base.Owner.CombatState.HittableEnemies)")
                         .Line($"await PowerCmd.Apply<{e.PowerId}>(choiceContext, other, {amt}, base.Owner, null);");
                        CSharpCodeGen.EmitSlowPercentFix(w, e, "other");
                        w.Close();
                        break;
                    case "RandomEnemies":
                        {
                            string times2 = e.RepeatIsStack ? "(int)base.Amount" : Math.Max(1, e.RepeatCount).ToString();
                            w.Open($"for (int k = 0; k < {times2}; k++)");
                            w.Line(RandomTargetLine);
                            w.Line("if (other is null) break;");
                            w.Line($"await PowerCmd.Apply<{e.PowerId}>(choiceContext, other, {amt}, base.Owner, null);");
                            CSharpCodeGen.EmitSlowPercentFix(w, e, "other");
                            w.Close();
                            break;
                        }
                    default:
                        EmitFoeBlock(w, foeFrom, foe =>
                            $"await PowerCmd.Apply<{e.PowerId}>(choiceContext, {foe}, {amt}, base.Owner, null);");
                        // EmitFoeBlock 生成的变量就叫 other
                        CSharpCodeGen.EmitSlowPercentFix(w, e, "other");
                        break;
                }
                break;

            // 击晕：状态触发器里也能用（CreatureCmd.Stun 不需要 choiceContext）
            case "Stun":
                CSharpCodeGen.EmitStunPublic(w, e, useX: false, cardTargetExpr: null,
                    enemiesExpr: "base.Owner.CombatState.HittableEnemies", playerExpr: "base.Owner.Player");
                break;

            // 给予卡牌关键词：状态触发器里也能给（数值 0 = 「这张牌自己」在状态里没有意义）
            case "GiveKeyword":
                CSharpCodeGen.EmitGiveKeyword(w, null, e, useX: false,
                    playerExpr: "base.Owner.Player", creatureExpr: "base.Owner", sourceExpr: "null", selfAllowed: false);
                break;

            // 强化指定卡牌：状态触发器里也能挂（挂在自己身上，只给那一张卡加伤害 / 格挡）
            case "BoostCard":
                w.Line(CSharpCodeGen.BoostMarker(e));
                w.Line($"await PowerCmd.Apply<{Naming.AmbientBoostPowerClass(e)}>(choiceContext, base.Owner, {amt}, base.Owner, null);");
                break;

            // 临时增益（本回合 +X，回合结束撤掉）：打的是生成的临时 Power
            case "TempPower":
                switch (e.TargetSide)
                {
                    case "Self":
                        w.Line($"await PowerCmd.Apply<{Naming.AmbientTempPowerClass(e)}>(choiceContext, base.Owner, {amt}, base.Owner, null);");
                        break;
                    case "AllEnemies":
                        w.Open("foreach (Creature other in base.Owner.CombatState.HittableEnemies)")
                         .Line($"await PowerCmd.Apply<{Naming.AmbientTempPowerClass(e)}>(choiceContext, other, {amt}, base.Owner, null);")
                         .Close();
                        break;
                    default:
                        EmitFoeBlock(w, foeFrom, foe =>
                            $"await PowerCmd.Apply<{Naming.AmbientTempPowerClass(e)}>(choiceContext, {foe}, {amt}, base.Owner, null);");
                        break;
                }
                break;

            default:
                w.Line($"// 这个效果种类在状态触发器里用不了（{e.Kind}）");
                break;
        }

        if (loop) w.Close();
        w.Close();   // 这条效果自己的作用域
    }

    /// <summary>
    /// 自定义状态的触发时机里造成的伤害。
    ///
    /// 用户要求：「自定义状态造成的伤害不能判定为角色造成的伤害」——
    /// 本体是靠 <c>dealer</c> 归因的（<c>CreatureCmd.Damage</c> 里
    /// <c>if (dealer != null &amp;&amp; dealer.Player != null &amp;&amp; target.Player == null) dealer.Player.ExtraFields.DamageDealt += …</c>），
    /// 所以这里传 **dealer: null**：伤害不计入「你造成的伤害」（本体「伤害最高」徽章、相关条件/统计都按这个走），
    /// 战斗记录里也写成「XX 受到了 N 点伤害」而不是「你造成了 N 点伤害」。
    /// 注意 <c>dealer</c> 只收非空 Creature 的重载不能传 null，必须用 7 个参数那条（末尾三个 null）。
    ///
    /// 同时保留 <c>ValueProp.Unpowered</c>：本体的力量/虚弱只对「PoweredAttack」生效
    /// （<c>props.IsPoweredAttack()</c> = 带 Move 且不带 Unpowered），所以伤害不随状态浮动；
    /// <c>dealer == null</c> 还顺带让荆棘/火焰屏障这类「被打就反弹」不会触发（它们都判 <c>dealer != null</c>）。
    /// 本体的「中毒跳伤 / 灭亡 / 窒息 / 闹鬼」这些状态造成的伤害就是这么写的（PoisonPower.Trigger 里 dealer 传 null）。
    /// </summary>
    private static void EmitDamage(CodeWriter w, EffectSpec e, string amt, string? foeFrom)
    {
        const string props = "ValueProp.Unpowered";
        switch (e.TargetSide)
        {
            case "Self":
                w.Line($"await CreatureCmd.Damage(choiceContext, base.Owner, {amt}, {props}, null, null, null);");
                break;
            case "AllEnemies":
                w.Open("foreach (Creature other in base.Owner.CombatState.HittableEnemies)")
                 .Line($"await CreatureCmd.Damage(choiceContext, other, {amt}, {props}, null, null, null);")
                 .Close();
                break;
            case "RandomEnemies":
                {
                    string times = e.RepeatIsStack ? "(int)base.Amount" : Math.Max(1, e.RepeatCount).ToString();
                    w.Open($"for (int k = 0; k < {times}; k++)");
                    w.Line(RandomTargetLine);
                    w.Line("if (other is null) break;");
                    w.Line($"await CreatureCmd.Damage(choiceContext, other, {amt}, {props}, null, null, null);");
                    w.Close();
                    break;
                }
            default:
                EmitFoeBlock(w, foeFrom, foe =>
                    $"await CreatureCmd.Damage(choiceContext, {foe}, {amt}, {props}, null, null, null);");
                break;
        }
    }

    /// <summary>
    /// 需要一个「敌方目标」的效果：优先用触发器能提供的那个（比如「打出牌后」就是这张牌的目标、
    /// 「受到伤害后」就是打你的那个敌人），拿不到就从可打的敌人里挑第一个。
    /// </summary>
    private static void EmitFoeBlock(CodeWriter w, string? foeFrom, Func<string, string> body)
    {
        if (foeFrom is not null)
        {
            w.Line($"Creature? other = {foeFrom};");
            w.Line("if (other is null || !other.IsEnemy || !other.IsAlive) other = base.Owner.CombatState.HittableEnemies.FirstOrDefault();");
        }
        else
        {
            w.Line("Creature? other = base.Owner.CombatState.HittableEnemies.FirstOrDefault();");
        }
        w.Open("if (other is not null)");
        w.Line(body("other"));
        w.Close();
    }
}
