using Sts2CharForge.Core.Profile;

namespace Sts2CharForge.Core.Generation;

/// <summary>
/// 「外观 / 台词」这类补丁的生成器：
///   1) 本体卡（初始卡组里的打击 / 防御）跟随本模组的卡框颜色与能量图标；
///   2) 死亡结算画面上那句话（本体没有「每个角色一句」的键，只能补丁换掉）；
///   3) 阵亡后台词（本体那条键只在联机 ping 时用得到，单人游戏改成阵亡时冒一个对话气泡）。
/// 都是纯外观/文本，全部包在 try/catch 里，出错也只是没效果，不影响玩法。
/// </summary>
public static class FlavorGen
{
    /// <summary>初始卡组里用到的本体卡（要跟随模组外观的那些）。</summary>
    public static List<string> VanillaSkinCards(CharacterProfile p) =>
        p.Cards.Where(c => c.IsVanillaCard)
            .Select(c => (c.ClassName ?? "").Trim())
            .Where(c => c.Length > 0)
            .Distinct(StringComparer.Ordinal)
            .ToList();

    public static bool NeedsVanillaSkin(CharacterProfile p) => VanillaSkinCards(p).Count > 0;

    /// <summary>
    /// 本体卡外观补丁：把「初始卡组里那几张本体卡」的 <c>VisualCardPool</c> 换成本模组的卡池。
    ///
    /// 为什么要这么做：本体的卡框材质、能量图标、牌堆底色、卡面横幅全都取自
    /// <c>CardModel.VisualCardPool</c>（本体自己也是这么做的 —— Clash / 双持 / 堑壕 都覆写了它，
    /// 为了借用铁甲战士的外观）。我们的初始卡组里放着本体的打击 / 防御，它们的卡池是铁甲战士的，
    /// 于是卡面会是红色铁甲风格 + 铁甲能量图标，跟角色其它卡不一致。
    /// 本体卡类不归我们写，改不了它的属性，所以用 Harmony 在这个 getter 上加 postfix。
    ///
    /// 只在这张卡**属于我们角色**时才换（<c>Owner.Character</c> 判断）——
    /// 否则玩铁甲战士时他的打击也会变成我们的外观。拿不到 Owner（牌库/图鉴里的规范模型）时不动。
    /// </summary>
    public static string VanillaSkinSource(CharacterProfile p)
    {
        var n = Naming.From(p);
        var names = VanillaSkinCards(p);
        if (names.Count == 0) return "";

        var w = new CodeWriter();
        w.Line("// <auto-generated> 本体卡外观补丁：初始卡组里的本体卡跟随本模组的卡框颜色 / 能量图标 </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line()
         .Line("/// <summary>")
         .Line("/// 让初始卡组里的本体卡（打击 / 防御）用本模组的外观。")
         .Line("/// 本体的卡框材质 / 能量图标 / 牌堆底色都取自 CardModel.VisualCardPool（Clash、双持 等本体卡")
         .Line("/// 也是靠覆写它来借别的角色的外观），我们改不了本体卡类，所以给这个 getter 挂 postfix。")
         .Line("/// 只在这张卡属于我们角色时生效（否则铁甲战士自己的打击也会被换外观）。")
         .Line("/// </summary>")
         .Line($"[HarmonyLib.HarmonyPatch(typeof(CardModel), \"get_VisualCardPool\")]")
         .Open($"internal static class Forge{n.CharClass}VanillaSkinPatch")
         .Open("private static void Postfix(CardModel __instance, ref CardPoolModel __result)")
         .Open("try")
         .Line("if (__instance is null) return;")
         .Line("if (!IsOurVanillaBasic(__instance.GetType().Name)) return;")
         .Line("Player? owner = __instance.Owner;")
         .Line($"if (owner is null || owner.Character is not {n.CharClass}) return;   // 别人（本体角色）的卡不动")
         .Line($"__result = ModelDb.CardPool<{n.CardPoolClass}>();")
         .Close()
         .Open("catch")
         .Line("// 纯外观，出错就当没这回事")
         .Close()
         .Close()
         .Line()
         .Open("private static bool IsOurVanillaBasic(string className)")
         .Line($"return className is {string.Join(" or ", names.Select(Lit.Str))};")
         .Close()
         .Close();
        return w.ToString();
    }

    public static bool NeedsDeathFlavor(CharacterProfile p) =>
        !string.IsNullOrWhiteSpace(p.DeathText) || !string.IsNullOrWhiteSpace(p.DeadBanterText);

    /// <summary>
    /// 死亡文本 / 阵亡后台词的补丁。
    ///
    /// 死亡描述文本：本体死亡结算画面上的那句话取自 run_history 表的通用文案
    /// （<c>NRunHistory.GetDeathQuote</c>：被谁杀死 / 放弃 / 假胜利…再套上引号），
    /// 表里**没有**「每个角色一句话」这种键，所以只能给这个方法挂 postfix 换成你写的那句。
    ///
    /// 阵亡后台词：本体只有 <c>characters</c> 表的 <c>&lt;角色&gt;.banter.dead.endTurnPing</c>，
    /// 而它只在**联机**里「回合结束 ping」时才显示（<c>FlavorSynchronizer</c>），单人游戏永远看不到。
    /// 所以这里额外在**自己阵亡的那一刻**用同一句话冒一个对话气泡（<c>NSpeechBubbleVfx</c>）。
    /// </summary>
    public static string DeathFlavorSource(CharacterProfile p)
    {
        var n = Naming.From(p);
        string death = (p.DeathText ?? "").Trim();
        string banter = (p.DeadBanterText ?? "").Trim();
        if (death.Length == 0 && banter.Length == 0) return "";

        var w = new CodeWriter();
        w.Line("// <auto-generated> 死亡文本 / 阵亡后台词 </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line();

        if (death.Length > 0)
        {
            w.Line("/// <summary>")
             .Line("/// 死亡结算画面上那句话：本体是 run_history 表里的通用文案（套上引号），")
             .Line("/// 没有「每个角色一句」的键 —— 所以在这里换成我们自己写的那句。")
             .Line("/// 只改我们自己的角色（别人的死亡文案不动）。")
             .Line("/// </summary>")
             .Line("[HarmonyLib.HarmonyPatch(typeof(MegaCrit.Sts2.Core.Nodes.Screens.RunHistoryScreen.NRunHistory),")
             .Line("    nameof(MegaCrit.Sts2.Core.Nodes.Screens.RunHistoryScreen.NRunHistory.GetDeathQuote))]")
             .Open($"internal static class Forge{n.CharClass}DeathQuotePatch")
             .Open("private static void Postfix(MegaCrit.Sts2.Core.Models.ModelId characterId, ref string __result)")
             .Open("try")
             .Line($"if (characterId != ModelDb.Character<{n.CharClass}>().Id) return;")
             .Line("// 引号沿用本体的那对（game_over_screen.ENCOUNTER_QUOTE_LEFT / RIGHT）")
             .Line("string left = new LocString(\"game_over_screen\", \"ENCOUNTER_QUOTE_LEFT\").GetRawText();")
             .Line("string right = new LocString(\"game_over_screen\", \"ENCOUNTER_QUOTE_RIGHT\").GetRawText();")
             .Line($"__result = left + {Lit.Str(death)} + right;")
             .Line($"Log.Info({Lit.Str(n.ModId + " - 死亡结算文案已替换为自定义文本")});")
             .Close()
             .Open("catch (Exception e)")
             .Line($"Log.Error({Lit.Str(n.ModId + " - 替换死亡结算文案失败（已忽略）：")} + e.Message);")
             .Close()
             .Close()
             .Close()
             .Line();
        }

        if (banter.Length > 0)
        {
            w.Line("/// <summary>")
             .Line("/// 阵亡后台词：本体那条 <c>&lt;角色&gt;.banter.dead.endTurnPing</c> 只有联机 ping 才会显示，")
             .Line("/// 单人游戏里永远看不到 —— 所以自己阵亡的那一刻直接冒一个对话气泡。")
             .Line("/// 挂在 CreatureCmd.Kill 上（本体所有死亡都会经过它），只认「死的是我们自己的角色」。")
             .Line("/// </summary>")
             .Line("[HarmonyLib.HarmonyPatch(typeof(CreatureCmd), \"Kill\", new[] { typeof(IReadOnlyCollection<Creature>), typeof(bool) })]")
             .Open($"internal static class Forge{n.CharClass}DeathBanterPatch")
             .Open("private static void Postfix(IReadOnlyCollection<Creature> creatures)")
             .Open("try")
             .Open("foreach (Creature creature in creatures)")
             .Line("if (creature?.Player is null) continue;")
             .Line($"if (creature.Player.Character is not {n.CharClass}) continue;")
             .Line($"Log.Info({Lit.Str(n.ModId + " - 角色阵亡，冒出阵亡后台词")});")
             .Line($"NSpeechBubbleVfx.Create({Lit.Str(banter)}, creature, 3.0, ModelDb.Character<{n.CharClass}>().SpeechBubbleColor);")
             .Line("break;")
             .Close()
             .Close()
             .Open("catch (Exception e)")
             .Line($"Log.Error({Lit.Str(n.ModId + " - 阵亡后台词显示失败（已忽略）：")} + e.Message);")
             .Close()
             .Close()
             .Close();
        }

        return w.ToString();
    }
}
