using Sts2CharForge.Core.Profile;

namespace Sts2CharForge.Core.Generation;

/// <summary>模组入口与全部 Harmony 补丁（把踩过的坑内建成模板）。</summary>
public static class PatchesGen
{
    /// <summary>建筑师对话行数（至少 1 行，否则本体 WinRun() 会空引用）。</summary>
    public static List<string> ArchitectLines(CharacterProfile p)
    {
        var lines = (p.ArchitectDialogue ?? string.Empty)
            .Replace("\r\n", "\n")
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();
        if (lines.Count == 0) lines.Add("……又是一个闯入者。");
        return lines;
    }

    /// <summary>
    /// 「先古卡」的卡框染色补丁（只在「诅咒 / 先古卡」页给先古卡设了卡框颜色时才生成）。
    ///
    /// **为什么非要有它**：先古卡（稀有度 Ancient）在卡面节点里**根本不显示普通的 Frame** ——
    /// <c>NCard.Reload()</c> 里写死了 <c>_frame.Visible = (稀有度 != Ancient)</c>，先古卡显示的是
    /// <c>AncientBorder</c> / <c>AncientTextBg</c> / <c>AncientBanner</c> 这三张先古专用贴图，
    /// 而它们**没有材质、只吃节点的 modulate**。所以「换 VisualCardPool 的卡框材质」对先古卡
    /// **一点效果都没有**（用户实测报过「改了 RRGGBB 没反应」）—— 那个材质只对诅咒这类普通卡生效。
    ///
    /// 这里在 NCard 每次 Reload 之后，把属于我们外观池的先古卡的 AncientBorder / AncientBanner
    /// 的 modulate **乘上**你填的颜色（本体自己也是这么给这两张图上色的：场景里 AncientBorder 的
    /// 默认 modulate 就是 (1, 0.978, 0.906, 0.502)）。乘的时候必须先记住「本体原本的 modulate」：
    /// Reload 会被反复调用、节点还会被复用，直接连乘会越来越暗。
    /// </summary>
    public static string StyledCardTintSource(CharacterProfile p)
    {
        var n = Naming.From(p);
        // 染什么颜色：勾了「自定义颜色」用填的 RRGGBB；选的是本体框色名（这时 FrameColor 是空的）
        // 就用那个框色对应的种子色 —— 不然这里会生成 new Godot.Color("#")，
        // 运行时解析不出来（Godot 会往日志里报错、染色也不生效，看上去就是「改了没反应」）。
        string hex = CardColorSpec.NormalizeHex(p.AncientStyle.FrameColor);
        if (hex.Length == 0) hex = CardColorSpec.SeedColorForFrame(p.AncientStyle.Frame);
        var w = new CodeWriter();
        w.Line("// <auto-generated> 先古卡的卡框染色补丁（先古卡不显示普通 Frame，只能改这几张图的 modulate） </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line()
         .Line("/// <summary>")
         .Line("/// 先古卡在卡面节点里不显示普通的 Frame（NCard.Reload 里 _frame.Visible = 稀有度 != Ancient），")
         .Line("/// 显示的是 AncientBorder / AncientTextBg / AncientBanner 三张先古专用贴图 —— 它们没有材质、")
         .Line("/// 只吃节点的 modulate。所以「换 VisualCardPool 的卡框材质」对先古卡没有效果，")
         .Line("/// 这里把 AncientBorder / AncientBanner 的 modulate 乘上「诅咒 / 先古卡」页里填的颜色。")
         .Line("/// 诅咒不是先古卡（Frame 可见），走的是卡框材质，不在这里重复染。")
         .Line("/// 这个补丁在模组入口里**手动打**（不是 PatchAll）：打不上也只是没有染色，不影响别的功能。")
         .Line("/// </summary>")
         .Open($"internal static class {n.CharClass}StyledCardTint")
         .Line("/// <summary>每个节点「本体原本的 modulate」：Reload 会被反复调用、节点还会被复用，")
         .Line("/// 记下原色才能每次都算出同一个结果（否则乘第二次就会更暗）。</summary>")
         .Line("private static readonly System.Runtime.CompilerServices.ConditionalWeakTable<Godot.TextureRect, Godot.Color[]> Original = new();")
         .Line()
         .Open("public static void Postfix(MegaCrit.Sts2.Core.Nodes.Cards.NCard __instance)")
         .Open("try")
         .Line("CardModel? card = __instance.Model;")
         .Line($"// 只有「先古卡 + 用了我们那个外观池」才染：{"#"+hex}（颜色是生成时就写死的）")
         .Line($"Godot.Color? tint = card is {{ Rarity: CardRarity.Ancient }} && card.VisualCardPool is {n.AncientStylePoolClass}")
         .Line($"    ? new Godot.Color({Lit.Str("#" + hex)})")
         .Line("    : null;")
         .Line("Recolor(__instance, \"%AncientBorder\", tint);   // 先古卡那一圈边框")
         .Line("Recolor(__instance, \"%AncientBanner\", tint);   // 顶部那条先古横幅（含火焰动画）")
         .Close()
         .Open("catch")
         .Line("// 纯外观：出错就当没这回事，绝不能影响卡牌本身")
         .Close()
         .Close()
         .Line()
         .Line("private static void Recolor(MegaCrit.Sts2.Core.Nodes.Cards.NCard card, string nodePath, Godot.Color? tint)")
         .Open("")
         .Line("Godot.TextureRect? rect = card.GetNodeOrNull<Godot.TextureRect>(nodePath);")
         .Line("if (rect is null) return;")
         .Line("if (!Original.TryGetValue(rect, out Godot.Color[]? bas))")
         .Open("")
         .Line("bas = new[] { rect.Modulate };")
         .Line("Original.Add(rect, bas);")
         .Close()
         .Line("// 染色 = 在本体原本的颜色上乘一遍（透明度保持不变，免得把先古边框那层半透明弄没）")
         .Line("Godot.Color want = tint is { } c")
         .Line("    ? new Godot.Color(bas[0].R * c.R, bas[0].G * c.G, bas[0].B * c.B, bas[0].A)")
         .Line("    : bas[0];")
         .Line("if (!rect.Modulate.IsEqualApprox(want)) rect.Modulate = want;")
         .Close()
         .Close()
         .Line();
        return w.ToString();
    }

    public static string ModEntrySource(CharacterProfile p)
    {        var n = Naming.From(p);
        var w = new CodeWriter();
        w.Line("// <auto-generated> 模组入口 </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line()
         .Line($"// 模组 ID：{n.ModId}")
         .Line("[ModInitializer(nameof(Initialize))]")
         .Open($"public static class {n.CharClass}ModInitializer")
         .Open("public static void Initialize()")
         .Open("try")
         .Line("// 让 Godot 检索本程序集，建立场景/脚本资源映射（模组里带场景时必须）")
         .Line("Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(System.Reflection.Assembly.GetExecutingAssembly());")
         .Line();

        w.Line("// 卡池/遗物池/药水池的成员统一在各自池类的 GenerateAllXxx() 里给出（含全部自有内容），")
         .Line("// 这里不再调用 ModHelper.AddModelToPool，避免同一张卡被重复登记进同一个池。")
         .Line()
         .Line($"var harmony = new HarmonyLib.Harmony({Lit.Str(n.ModId)});")
         .Line("harmony.PatchAll(System.Reflection.Assembly.GetExecutingAssembly());");

        // 「先古卡染色」补丁单独手动打：它是打在 NCard 的**私有方法** Reload 上的，
        // 万一本体改了方法名，绝不能连累整个模组加载（PatchAll 抛异常的话角色注册也一起没了）。
        if (p.AncientStyle.Any)
        {
            w.Line()
             .Line("// 先古卡的卡框染色（见 StyledCardTint.cs）：单独手动打，失败了只丢染色、不影响别的补丁")
             .Open("try")
             .Line("var __tintTarget = HarmonyLib.AccessTools.Method(typeof(MegaCrit.Sts2.Core.Nodes.Cards.NCard), \"Reload\");")
             .Line("if (__tintTarget is not null)")
             .Line($"    harmony.Patch(__tintTarget, postfix: new HarmonyLib.HarmonyMethod(typeof({n.CharClass}StyledCardTint), nameof({n.CharClass}StyledCardTint.Postfix)));")
             .Line("else")
             .Line($"    Log.Warn({Lit.Str("先古卡染色补丁没打上：找不到 NCard.Reload（本体的卡面节点可能改过）")});")
             .Close()
             .Open("catch (Exception e)")
             .Line($"Log.Warn({Lit.Str("先古卡染色补丁没打上：")} + e.Message);")
             .Close();
        }

        w.Line()
         .Line($"Log.Info({Lit.Str(n.ModId + " - 加载成功!")});")
         .Close()
         .Open("catch (Exception e)")
         .Line($"Log.Error({Lit.Str(n.ModId + " - 加载失败")});")
         .Line("Log.Error(e.Message);")
         .Close()
         .Close()
         .Close();
        return w.ToString();
    }

    public static string PatchesSource(CharacterProfile p)
    {
        var n = Naming.From(p);
        int lineCount = ArchitectLines(p).Count;

        var w = new CodeWriter();
        w.Line("// <auto-generated> Harmony 补丁：角色注册 / 音效与成就 / 结算保护 / 建筑师对话 </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line()
         .Line("// 把自定义角色加进可选角色列表（本体的 AllCharacters 是硬编码数组）")
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCharacters), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}RegistrationPatch")
         .Open("static void Postfix(ref IEnumerable<CharacterModel> __result)")
         .Line($"__result = __result.Append(ModelDb.Character<{n.CharClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("// ============================================================")
         .Line("// 卡池聚合属性（本体是 _allXxx ??= ... 的惰性缓存）：")
         .Line("// 只要别的模组/初始化流程在我们注册角色之前读过一次，缓存里就永远没有我们的卡池，")
         .Line("// 结果 ModelDb.Preload() 遍历 AllCards 时 CardModel.Pool 查不到 → ")
         .Line("// InvalidProgramException: Card CARD.XXX is not in any card pool!（卡牌无法识别）")
         .Line("// 每个 getter 都挂 postfix 追加自己的内容，这样与缓存时序无关。")
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCharacterCardPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}CardPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<CardPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.CardPool<{n.CardPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCardPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllCardPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<CardPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.CardPool<{n.CardPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCards), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllCardsPatch")
         .Open("static void Postfix(ref IEnumerable<CardModel> __result)")
         .Line($"__result = __result.Concat(ModelDb.CardPool<{n.CardPoolClass}>().AllCards)")
         .Line($"    .Concat(ModelDb.Character<{n.CharClass}>().StartingDeck).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCharacterPotionPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}PotionPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<PotionPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.PotionPool<{n.PotionPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllPotionPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllPotionPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<PotionPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.PotionPool<{n.PotionPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllRelicPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllRelicPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<RelicPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.RelicPool<{n.RelicPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllRelics), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllRelicsPatch")
         .Open("static void Postfix(ref IEnumerable<RelicModel> __result)")
         .Line($"__result = __result.Concat(ModelDb.RelicPool<{n.RelicPoolClass}>().AllRelics)")
         .Line($"    .Concat(ModelDb.Character<{n.CharClass}>().StartingRelics).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllPotions), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllPotionsPatch")
         .Open("static void Postfix(ref IEnumerable<PotionModel> __result)")
         .Line($"__result = __result.Concat(ModelDb.PotionPool<{n.PotionPoolClass}>().AllPotions).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("// 本体 AttackSfx/CastSfx/DeathSfx 按角色 ID 拼路径且不可覆写 → 复用铁甲战士的");

        foreach (var prop in new[] { "AttackSfx", "CastSfx", "DeathSfx" })
        {
            w.Line($"[HarmonyLib.HarmonyPatch(typeof(CharacterModel), nameof(CharacterModel.{prop}), HarmonyLib.MethodType.Getter)]")
             .Open($"public static class {n.CharClass}{prop}Patch")
             .Open("static void Postfix(CharacterModel __instance, ref string __result)")
             .Open($"if (__instance is {n.CharClass})")
             .Line($"__result = ModelDb.Character<Ironclad>().{prop};")
             .Close()
             .Close()
             .Close()
             .Line();
        }

        w.Line("// RunWonAchievement 会 Enum.Parse<Achievement>(\"<角色ID>Win\")，自定义角色会抛异常 → 借用铁甲战士的")
         .Line("[HarmonyLib.HarmonyPatch(typeof(CharacterModel), nameof(CharacterModel.RunWonAchievement), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}RunWonAchievementPatch")
         .Open("static void Postfix(CharacterModel __instance, ref Achievement __result)")
         .Open($"if (__instance is {n.CharClass})")
         .Line("__result = ModelDb.Character<Ironclad>().RunWonAchievement;")
         .Close()
         .Close()
         .Close()
         .Line()
         .Line("// ============================================================")
         .Line("// 精英/Boss 结算保护：本体按硬编码的 6 个官方角色做类型判断，")
         .Line("// 自定义角色会抛 ArgumentOutOfRangeException(\"character\") → 精英/Boss 打完不结算。")
         .Line("// ============================================================")
         .Open("internal static class ForgeVanillaCharacterGuard")
         .Line("public static bool IsVanilla(CharacterModel? character) =>")
         .Line("    character is Ironclad or Silent or Regent or Defect or Necrobinder or Deprived;")
         .Close()
         .Line();

        foreach (var (method, label) in new[]
                 {
                     ("CheckFifteenElitesDefeatedEpoch", "精英房"),
                     ("CheckFifteenBossesDefeatedEpoch", "Boss 房"),
                     ("ObtainCharUnlockEpoch", "幕 Boss 解锁纪元"),
                 })
        {
            w.Line($"// {label}")
             .Line($"[HarmonyLib.HarmonyPatch(typeof(ProgressSaveManager), \"{method}\")]")
             .Open($"public static class Forge{method}Guard")
             .Line("[HarmonyLib.HarmonyPriority(HarmonyLib.Priority.First)]")
             .Open("static bool Prefix(Player localPlayer)")
             .Line("return ForgeVanillaCharacterGuard.IsVanilla(localPlayer.Character);")
             .Close()
             .Close()
             .Line();
        }

        w.Line("// ============================================================")
         .Line("// 最终 Boss「建筑师」通关对话：本体只给官方角色写了对话 → 自定义角色 Dialogue = null，")
         .Line("// TheArchitect.WinRun() 里 Dialogue.EndAttackers 没判空 → 空引用 → 通关结算丢失。")
         .Line("// ============================================================")
         .Line("[HarmonyLib.HarmonyPatch(typeof(TheArchitect), nameof(TheArchitect.DialogueSet), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}ArchitectDialoguePatch")
         .Open("static void Postfix(AncientDialogueSet __result)")
         .Line($"string charKey = ModelDb.GetId(typeof({n.CharClass})).Entry;")
         .Open("if (__result.CharacterDialogues.ContainsKey(charKey))")
         .Line("return;")
         .Close()
         .Line()
         .Line($"// {lineCount} 行对话；IsRepeating + VisitIndex(null) → 每次通关都有效")
         .Line($"AncientDialogue dialogue = new AncientDialogue({string.Join(", ", Enumerable.Repeat("\"\"", lineCount))}) {{ IsRepeating = true }};")
         .Line()
         .Line("__result.CharacterDialogues[charKey] = new List<AncientDialogue> { dialogue };")
         .Line()
         .Line("// 本体的 PopulateLocKeys 在我们的 Postfix 之前已跑过，这里补一次填充 LineText / NextButtonText")
         .Line("__result.PopulateLocKeys(\"THE_ARCHITECT\");")
         .Close()
         .Close();

        return w.ToString();
    }
}
