using Sts2CharForge.Core.Profile;

namespace Sts2CharForge.Core.Generation;

/// <summary>模组入口与全部 Harmony 补丁（把踩过的坑内建成模板）。</summary>
public static class PatchesGen
{
    /// <summary>建筑师对话行数（至少 1 行，否则本体 WinRun() 会空引用）。</summary>
    public static List<string> ArchitectLines(CharacterProfile p)
    {
        var lines = (p.ArchitectDialogue ?? string.Empty)
            .Replace("\r\n", "\n")
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();
        if (lines.Count == 0) lines.Add("……又是一个闯入者。");
        return lines;
    }

    public static string ModEntrySource(CharacterProfile p)
    {
        var n = Naming.From(p);
        var w = new CodeWriter();
        w.Line("// <auto-generated> 模组入口 </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line()
         .Line($"// 模组 ID：{n.ModId}")
         .Line("[ModInitializer(nameof(Initialize))]")
         .Open($"public static class {n.CharClass}ModInitializer")
         .Open("public static void Initialize()")
         .Open("try")
         .Line("// 让 Godot 检索本程序集，建立场景/脚本资源映射（模组里带场景时必须）")
         .Line("Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(System.Reflection.Assembly.GetExecutingAssembly());")
         .Line();

        w.Line("// 卡池/遗物池/药水池的成员统一在各自池类的 GenerateAllXxx() 里给出（含全部自有内容），")
         .Line("// 这里不再调用 ModHelper.AddModelToPool，避免同一张卡被重复登记进同一个池。")
         .Line()
         .Line($"var harmony = new HarmonyLib.Harmony({Lit.Str(n.ModId)});")
         .Line("harmony.PatchAll(System.Reflection.Assembly.GetExecutingAssembly());")
         .Line()
         .Line($"Log.Info({Lit.Str(n.ModId + " - 加载成功!")});")
         .Close()
         .Open("catch (Exception e)")
         .Line($"Log.Error({Lit.Str(n.ModId + " - 加载失败")});")
         .Line("Log.Error(e.Message);")
         .Close()
         .Close()
         .Close();
        return w.ToString();
    }

    public static string PatchesSource(CharacterProfile p)
    {
        var n = Naming.From(p);
        int lineCount = ArchitectLines(p).Count;

        var w = new CodeWriter();
        w.Line("// <auto-generated> Harmony 补丁：角色注册 / 音效与成就 / 结算保护 / 建筑师对话 </auto-generated>")
         .Line($"namespace {n.Namespace};")
         .Line()
         .Line("// 把自定义角色加进可选角色列表（本体的 AllCharacters 是硬编码数组）")
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCharacters), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}RegistrationPatch")
         .Open("static void Postfix(ref IEnumerable<CharacterModel> __result)")
         .Line($"__result = __result.Append(ModelDb.Character<{n.CharClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("// ============================================================")
         .Line("// 卡池聚合属性（本体是 _allXxx ??= ... 的惰性缓存）：")
         .Line("// 只要别的模组/初始化流程在我们注册角色之前读过一次，缓存里就永远没有我们的卡池，")
         .Line("// 结果 ModelDb.Preload() 遍历 AllCards 时 CardModel.Pool 查不到 → ")
         .Line("// InvalidProgramException: Card CARD.XXX is not in any card pool!（卡牌无法识别）")
         .Line("// 每个 getter 都挂 postfix 追加自己的内容，这样与缓存时序无关。")
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCharacterCardPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}CardPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<CardPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.CardPool<{n.CardPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCardPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllCardPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<CardPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.CardPool<{n.CardPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCards), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllCardsPatch")
         .Open("static void Postfix(ref IEnumerable<CardModel> __result)")
         .Line($"__result = __result.Concat(ModelDb.CardPool<{n.CardPoolClass}>().AllCards)")
         .Line($"    .Concat(ModelDb.Character<{n.CharClass}>().StartingDeck).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllCharacterPotionPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}PotionPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<PotionPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.PotionPool<{n.PotionPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllPotionPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllPotionPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<PotionPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.PotionPool<{n.PotionPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllRelicPools), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllRelicPoolsPatch")
         .Open("static void Postfix(ref IEnumerable<RelicPoolModel> __result)")
         .Line($"__result = __result.Append(ModelDb.RelicPool<{n.RelicPoolClass}>()).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllRelics), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllRelicsPatch")
         .Open("static void Postfix(ref IEnumerable<RelicModel> __result)")
         .Line($"__result = __result.Concat(ModelDb.RelicPool<{n.RelicPoolClass}>().AllRelics)")
         .Line($"    .Concat(ModelDb.Character<{n.CharClass}>().StartingRelics).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("[HarmonyLib.HarmonyPatch(typeof(ModelDb), nameof(ModelDb.AllPotions), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}AllPotionsPatch")
         .Open("static void Postfix(ref IEnumerable<PotionModel> __result)")
         .Line($"__result = __result.Concat(ModelDb.PotionPool<{n.PotionPoolClass}>().AllPotions).Distinct();")
         .Close()
         .Close()
         .Line()
         .Line("// 本体 AttackSfx/CastSfx/DeathSfx 按角色 ID 拼路径且不可覆写 → 复用铁甲战士的");

        foreach (var prop in new[] { "AttackSfx", "CastSfx", "DeathSfx" })
        {
            w.Line($"[HarmonyLib.HarmonyPatch(typeof(CharacterModel), nameof(CharacterModel.{prop}), HarmonyLib.MethodType.Getter)]")
             .Open($"public static class {n.CharClass}{prop}Patch")
             .Open("static void Postfix(CharacterModel __instance, ref string __result)")
             .Open($"if (__instance is {n.CharClass})")
             .Line($"__result = ModelDb.Character<Ironclad>().{prop};")
             .Close()
             .Close()
             .Close()
             .Line();
        }

        w.Line("// RunWonAchievement 会 Enum.Parse<Achievement>(\"<角色ID>Win\")，自定义角色会抛异常 → 借用铁甲战士的")
         .Line("[HarmonyLib.HarmonyPatch(typeof(CharacterModel), nameof(CharacterModel.RunWonAchievement), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}RunWonAchievementPatch")
         .Open("static void Postfix(CharacterModel __instance, ref Achievement __result)")
         .Open($"if (__instance is {n.CharClass})")
         .Line("__result = ModelDb.Character<Ironclad>().RunWonAchievement;")
         .Close()
         .Close()
         .Close()
         .Line()
         .Line("// ============================================================")
         .Line("// 精英/Boss 结算保护：本体按硬编码的 6 个官方角色做类型判断，")
         .Line("// 自定义角色会抛 ArgumentOutOfRangeException(\"character\") → 精英/Boss 打完不结算。")
         .Line("// ============================================================")
         .Open("internal static class ForgeVanillaCharacterGuard")
         .Line("public static bool IsVanilla(CharacterModel? character) =>")
         .Line("    character is Ironclad or Silent or Regent or Defect or Necrobinder or Deprived;")
         .Close()
         .Line();

        foreach (var (method, label) in new[]
                 {
                     ("CheckFifteenElitesDefeatedEpoch", "精英房"),
                     ("CheckFifteenBossesDefeatedEpoch", "Boss 房"),
                     ("ObtainCharUnlockEpoch", "幕 Boss 解锁纪元"),
                 })
        {
            w.Line($"// {label}")
             .Line($"[HarmonyLib.HarmonyPatch(typeof(ProgressSaveManager), \"{method}\")]")
             .Open($"public static class Forge{method}Guard")
             .Line("[HarmonyLib.HarmonyPriority(HarmonyLib.Priority.First)]")
             .Open("static bool Prefix(Player localPlayer)")
             .Line("return ForgeVanillaCharacterGuard.IsVanilla(localPlayer.Character);")
             .Close()
             .Close()
             .Line();
        }

        w.Line("// ============================================================")
         .Line("// 最终 Boss「建筑师」通关对话：本体只给官方角色写了对话 → 自定义角色 Dialogue = null，")
         .Line("// TheArchitect.WinRun() 里 Dialogue.EndAttackers 没判空 → 空引用 → 通关结算丢失。")
         .Line("// ============================================================")
         .Line("[HarmonyLib.HarmonyPatch(typeof(TheArchitect), nameof(TheArchitect.DialogueSet), HarmonyLib.MethodType.Getter)]")
         .Open($"public static class {n.CharClass}ArchitectDialoguePatch")
         .Open("static void Postfix(AncientDialogueSet __result)")
         .Line($"string charKey = ModelDb.GetId(typeof({n.CharClass})).Entry;")
         .Open("if (__result.CharacterDialogues.ContainsKey(charKey))")
         .Line("return;")
         .Close()
         .Line()
         .Line($"// {lineCount} 行对话；IsRepeating + VisitIndex(null) → 每次通关都有效")
         .Line($"AncientDialogue dialogue = new AncientDialogue({string.Join(", ", Enumerable.Repeat("\"\"", lineCount))}) {{ IsRepeating = true }};")
         .Line()
         .Line("__result.CharacterDialogues[charKey] = new List<AncientDialogue> { dialogue };")
         .Line()
         .Line("// 本体的 PopulateLocKeys 在我们的 Postfix 之前已跑过，这里补一次填充 LineText / NextButtonText")
         .Line("__result.PopulateLocKeys(\"THE_ARCHITECT\");")
         .Close()
         .Close();

        return w.ToString();
    }
}
